# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IltXssPklLJgQbPQvA2nF6Dj76ms4S4F
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Sample data creation
years = range(2010, 2021)
countries = ['USA', 'China', 'India', 'Russia']
indicators = ['Electricity Access', 'CO2 Emissions', 'Population', 'Renewable Energy']

data = {
    'Year': np.random.choice(years, 40),
    'Country': np.random.choice(countries, 40),
    'Electricity Access': np.random.uniform(50, 100, 40),
    'CO2 Emissions': np.random.uniform(1000, 5000, 40),
    'Population': np.random.uniform(1e6, 1e9, 40),
    'Renewable Energy': np.random.uniform(10, 50, 40)
}

# Create DataFrame
df = pd.DataFrame(data)

# Statistical properties of indicators for each country
for country in countries:
    country_data = df[df['Country'] == country]
    print(f"Statistics for {country}:")
    print(country_data.describe())
    print()

# Comparison of indicators across countries with trend lines
for indicator in indicators:
    plt.figure(figsize=(12, 6))
    plt.title(f"Comparison of {indicator} across countries")
    for country in countries:
        country_data = df[df['Country'] == country]
        plt.plot(country_data['Year'], country_data[indicator], label=country)
        z = np.polyfit(country_data['Year'], country_data[indicator], 1)
        p = np.poly1d(z)
        plt.plot(country_data['Year'], p(country_data['Year']), linestyle='dashed')
    plt.xlabel("Year")
    plt.ylabel(indicator)
    plt.legend()
    plt.grid(True)
    plt.show()

# Histograms for each indicator
for indicator in indicators:
    plt.figure(figsize=(8, 6))
    plt.title(f"Histogram of {indicator}")
    sns.histplot(df[indicator], bins=10, kde=True)
    plt.xlabel(indicator)
    plt.ylabel("Frequency")
    plt.grid(True)
    plt.show()

# Scatter plots to explore relationships between indicators
sns.pairplot(df[indicators])
plt.suptitle("Pairplot of Indicators", y=1.02)
plt.show()

# Bar plots for mean values of indicators across countries
for indicator in indicators:
    plt.figure(figsize=(8, 6))
    plt.title(f"Mean {indicator} across countries")
    sns.barplot(x='Country', y=indicator, data=df, estimator=np.mean)
    plt.xlabel("Country")
    plt.ylabel(f"Mean {indicator}")
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.show()